name: Helm Chart Linting

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Install YAML Linter (`yamllint`)
        run: sudo apt update && sudo apt install -y yamllint

      - name: Install Chart Testing (ct)
        uses: helm/chart-testing-action@v2.6.0

      - name: Run Helm Lint
        run: helm lint charts/nfspvc-operator

      - name: Run Chart Testing Lint
        run: ct lint --charts charts/nfspvc-operator